In [4]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda')

(device(type='cpu'), device(type='cuda'))

In [5]:
torch.cuda.device_count()

0

In [ ]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    devices=[torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(),try_gpu(10),try_all_gpus()    

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [10]:
x=torch.tensor([1,2,3])
x.device

device(type='cpu')

In [11]:
x=torch.ones(2,3,device=try_gpu())
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
y=torch.rand(2,3,device=try_gpu(1))
y

tensor([[0.3309, 0.8414, 0.8356],
        [0.1800, 0.6641, 0.3997]])

In [ ]:
z=x.cpu()   #电脑无gpu
print(x)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
y+z

tensor([[2.3309, 2.8414, 2.8356],
        [2.1800, 2.6641, 2.3997]])

In [17]:
z.cpu()is z

True