自定义层-不带参数

In [4]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x - x.mean()

layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
y=net(torch.randn(4,8))
y.mean()

tensor(6.9849e-09, grad_fn=<MeanBackward0>)

自定义层-带参数

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,units))
        self.bias=nn.Parameter(torch.randn(units,))

    def forward(self,x):
        linear=torch.matmul(x,self.weight.data)+self.bias.data
        return F.relu(linear)
    
linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[-0.4902, -0.6470,  1.0397],
        [-0.9512,  0.7081,  0.9721],
        [ 0.9348,  0.8178, -0.5954],
        [-0.9538,  1.1163, -0.0032],
        [-0.9411, -1.8838, -0.7556]], requires_grad=True)

In [8]:
linear(torch.rand(2,5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.8746, 0.0000]])

In [9]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.randn(2,64))

tensor([[7.6165],
        [0.0000]])